# Site settings
title: Proyek Mekatronika
description: A simple description of my site
baseurl: "/Proyek-Mekatronika" # the subpath of your site, e.g. /blog
url: "https://github.com/BeneMeka100/Proyek-Mekatronika" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - netlify/functions

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# Markdown settings
kramdown:
  input: GFM

# Jekyll commands
jekyll_commands:
  build: "jekyll build"
  serve: "jekyll serve"
  clean: "jekyll clean"

# Netlify settings
netlify:
  runtime: "Not set"
  base_directory: "/"
  package_directory: "Not set"
  build_command: "jekyll build"
  publish_directory: "_site"
  functions_directory: "netlify/functions"
  deploy_log_visibility: "Logs are public"
  build_status: "Active"
